-- MySQL Script generated by MySQL Workbench
-- 02/04/15 22:08:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema high-school
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `high-school` ;

-- -----------------------------------------------------
-- Schema high-school
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `high-school` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `high-school` ;

-- -----------------------------------------------------
-- Table `high-school`.`Alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `high-school`.`Alumno` (
  `id_alumno` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `registro` INT(10) NOT NULL,
  `nacimiento` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id_alumno`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_alumno_UNIQUE` ON `high-school`.`Alumno` (`id_alumno` ASC);


-- -----------------------------------------------------
-- Table `high-school`.`Profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `high-school`.`Profesor` (
  `id_profesor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `nacimiento` DATE NOT NULL,
  PRIMARY KEY (`id_profesor`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idTeacher_UNIQUE` ON `high-school`.`Profesor` (`id_profesor` ASC);


-- -----------------------------------------------------
-- Table `high-school`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `high-school`.`Curso` (
  `id_curso` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `nombrep` VARCHAR(45) NOT NULL,
  `horas_semana` INT NOT NULL,
  `tiempo` INT NOT NULL,
  `Profesor_id_profesor` INT NOT NULL,
  PRIMARY KEY (`id_curso`),
  CONSTRAINT `fk_Curso_Profesor1`
    FOREIGN KEY (`Profesor_id_profesor`)
    REFERENCES `high-school`.`Profesor` (`id_profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idCourse_UNIQUE` ON `high-school`.`Curso` (`id_curso` ASC);

CREATE INDEX `fk_Curso_Profesor1_idx` ON `high-school`.`Curso` (`Profesor_id_profesor` ASC);


-- -----------------------------------------------------
-- Table `high-school`.`Alumnocurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `high-school`.`Alumnocurso` (
  `id_alumnocurso` INT NOT NULL AUTO_INCREMENT,
  `al_id_alumno` INT NOT NULL,
  `al_id_curso` INT NOT NULL,
  `primero` INT NULL,
  `segundo` INT NULL,
  `tercero` INT NULL,
  `final` INT NULL,
  PRIMARY KEY (`id_alumnocurso`),
  CONSTRAINT `al_id_alumno`
    FOREIGN KEY (`al_id_alumno`)
    REFERENCES `high-school`.`Alumno` (`id_alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `al_id_curso`
    FOREIGN KEY (`al_id_curso`)
    REFERENCES `high-school`.`Curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_alumnocurso_UNIQUE` ON `high-school`.`Alumnocurso` (`id_alumnocurso` ASC);

CREATE INDEX `al_id_alumno_idx` ON `high-school`.`Alumnocurso` (`al_id_alumno` ASC);

CREATE INDEX `al_id_curso_idx` ON `high-school`.`Alumnocurso` (`al_id_curso` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
